[package]
name = "msrs"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
itertools = "0.14.0"
once_cell = "1.21.3"
reqwest = { version = "0.12.23", features = ["rustls-tls"] }
scraper = "0.24.0"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
